API Gateway Infrastructure
lamarmeigs/terraform-aws-lambda-apigateway pull request #5
Opened 2024-04-19 13:54 UTC by tdemint10

Adding the necessary AWS infrastructure to support an API via API Gateway. This includes a helper Python file to enrich a provided OpenAPI spec for upload.

2024-04-19 21:30 UTC, lamarmeigs requested changes
We might need to test this more or break it down so that the Python script is tackled separately. It's raising havoc during testing.

2024-04-19 21:30 UTC, lamarmeigs commented on examples/simple/main.tf
> +        invoke_arn = "arn::GreetingLambda"
![](https://i.kym-cdn.com/photos/images/newsfeed/000/000/681/what-you-did-there-i-see-it.thumbnail.jpg)

This satisfies whatever static validation is provided by `terraform validate`, but running a plan on it uncovers lots of errors, and not just because this isn't a valid ARN. There are a few things hinky between this Terraform code and the `enrich_spec.py` script -- inputs aren't being processed successfully.

Give it a plan, yourself, to try.

2024-04-19 21:30 UTC, lamarmeigs commented on api.tf
> +    specification      = jsonencode(yamldecode(var.api_specification))
I encountered this error when giving the example a spin:
```
│ Error: Invalid function argument
│
│   on ../../api.tf line 16, in data "external" "enriched_specification":
│   16:     specification      = jsonencode(yamldecode(var.api_specification))
│     ├────────────────
│     │ while calling yamldecode(src)
│     │ var.api_specification is null
│
│ Invalid value for "src" parameter: argument must not be null.
```

Evidently, `yamldecode` rejects `var.api_specification`'s default value of `null`. Unless you can find a clever default value, you may be stuck using a ternary if:

```hcl
specification = var.api_specification == null ? null : jsonencode(yamldecode(var.api_specification))
```

2024-04-19 21:30 UTC, lamarmeigs commented on enrich_spec.py
> +    ```
Could you double-check this code sample against the actual Terraform? It looks like there are some outdated examples, eg. `validate_requests` instead of `validation`, `authorizers` isn't json encoded...

2024-04-19 21:30 UTC, lamarmeigs commented on examples/simple/main.tf
> +        invoke_arn = "arn::GreetingLambda"
And yes, once that's done, we really should show the example working with an actual Lambda function. We could even use the other module to reduce the amount of HCL:

```hcl
module "lambda_functions" {
  source = "git@github.com:lamarmeigs/terraform-aws-pipenv-lambdas.git?ref=v1.1.1"

  packages = ["src"]
  runtime  = "python3.10"
  root     = "."
  service  = "example-service-${random_string.suffix.result}"
  functions = {
    GetGreeting = {
      handler = "src.handlers.get_greeting"
    }
  }
}

module "apigateway" {
  source = "../.."

  domain_certificate_arn = "arn::MyServiceDomain"
  domain_name            = "my-service.com"
  service                = "MyService"

  endpoints = {
    "GET /v1/greeting" : {
      lambda = {
        name       = module.lambda_functions.functions.name
        invoke_arn = module.lambda_functions.functions.invoke_arn
      }
    }
  }
}
```

2024-04-19 21:30 UTC, lamarmeigs commented on enrich_spec.py
Does this repo need a `.flake8` and/or black configuration? I'm getting lots of line length warnings in my editor.

2024-04-22 15:06 UTC, tdemint10 commented
> We might need to test this more or break it down so that the Python script is tackled separately. It's raising havoc during testing.

I think you are right and it would be better to tackle the Python piece separately since that is going to require some more thought and changes than I originally expected. I will work on getting the PR updated and re-request review when ready

2024-04-22 15:07 UTC, tdemint10 commented on enrich_spec.py
> +    ```
Handling in separate PR

2024-04-22 15:07 UTC, tdemint10 commented on enrich_spec.py
Handling in separate PR

2024-04-22 15:07 UTC, tdemint10 commented on api.tf
> +    specification      = jsonencode(yamldecode(var.api_specification))
Handling in separate PR

2024-04-22 15:09 UTC, tdemint10 commented on examples/simple/main.tf
> +        invoke_arn = "arn::GreetingLambda"
All good points, I took a short-cut to just pass the validation. I will extend with your suggestions

2024-04-29 18:58 UTC, tdemint10 commented on examples/simple/main.tf
> +        invoke_arn = "arn::GreetingLambda"
Extended this example to actually use the lambda module. Confirmed that we are able to get a valid plan now

2024-04-30 12:08 UTC, lamarmeigs requested changes
I'm still getting errors when trying to apply. The examples won't be much good unless they work 😞

2024-04-30 12:08 UTC, lamarmeigs commented on examples/simple/main.tf
> +  source_path = "./"
Using the current directory as the source path means that when we create the zip file, it will try to capture all of the Terraform code and its dependencies (everything in `.terraform/`). That, apparently, leads to an error, as the file size surpasses what zip can handle.

I'd recommend changing this to `src`, and updating the `handler` argument accordingly.

2024-04-30 12:08 UTC, lamarmeigs commented on examples/simple/main.tf
> +  domain_name            = "MyServiceDomain"
This results with the following error:

```
│ Error: creating API Gateway Domain Name (MyServiceDomain): operation error API Gateway: CreateDomainName, https response error StatusCode: 400, RequestID: ffdeb7c2-8096-46e0-afc9-d46fbd4dbb96, BadRequestException: Invalid Domain Name.
```

I'm not entirely sure what the problem is, but I'm guessing it wants a FQDN. If that doesn't work, it might be worth ditching the domain pathing in this early PR, as well. That would require removing `aws_api_gateway_domain_name`, `aws_api_gateway_base_path_mapping`, and their related outputs.

(I suspect the certificate will cause a similar error.)

2024-04-30 12:08 UTC, lamarmeigs commented on api.tf
> +}
With the removed spec, I'm getting this error during apply:

```
│ Error: creating API Gateway Deployment: operation error API Gateway: CreateDeployment, https response error StatusCode: 400, RequestID: 3d4a4bb5-f6e7-4d0b-8308-d7677c290c94, BadRequestException: The REST API doesn't contain any methods
```

Think we could add a dummy, unenriched OpenAPI spec to this? Just to give it something to act on.

2024-04-30 16:49 UTC, tdemint10 commented on examples/simple/main.tf
> +  domain_name            = "MyServiceDomain"
I am going to remove this from this PR to simplify

2024-05-09 12:22 UTC, lamarmeigs approved these changes
There's still something hinky going on: I can test through the APIGateway console, but actually sending a request to the randomly-generated domain results in a 403 Forbidden. I also seem to be incapable of generating access logs to help debug.

I'm going to assume that error is tied up with the custom domain and its default path routing. This should be plenty to get us started as a v0.0.1!

2024-05-09 12:22 UTC, lamarmeigs commented on iam.tf
> +}
This file seems to use two different strategies for defining IAM policies: one line 8, we use a `aws_iam_policy_document`, but here, we define the JSON directly.

I'd generally recommend using the former in most cases. Should be easy to rewrite, though!

```suggestion
resource "aws_iam_role" "api_gateway_account_role" {
  name               = "api-gateway-account-role"
  assume_role_policy = data.aws_iam_policy_document.api_gateway_account_role_trust.json
}

data "aws_iam_policy_document" "api_gateway_account_role_trust" {
  version = "2012-10-17"
  statement {
    effect = "Allow"
    principals {
      type        = "Service"
      identifiers = "apigateway.amazonaws.com"
    }
    actions = ["sts:AssumeRole"]
  }
}
```

Same for the `aws_iam_role_policy`, below.

2024-05-09 12:22 UTC, lamarmeigs commented on outputs.tf
Could we also output `aws_api_gateway_deployment.invoke_url`? Until we sort out the custom URL, that'll be where we invoke the newly-created API endpoints.

2024-05-09 19:07 UTC, merged